name: Build Package

"on":  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      upload-to-s3:
        type: boolean
        required: false
        default: false
      upload-to-testpypi:
        type: boolean
        required: false
        default: false
      upload-to-pypi:
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      upload-to-s3:
        type: boolean
        required: false
        default: false
      upload-to-testpypi:
        type: boolean
        required: false
        default: false
      upload-to-pypi:
        type: boolean
        required: false
        default: false
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: |
          python -m build

      - name: Validate built packages
        run: |
          ls -ahl dist/
          ./scripts/validate_wheels_for_release.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: ./dist/
          retention-days: 7

      - name: Upload to internal S3
        if: ${{ inputs.upload-to-s3 && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
        run: |
          aws s3 sync dist s3://kumo-mcp-packages/kumo-rfm-mcp/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      - name: Upload to TestPyPI
        if: ${{ inputs.upload-to-testpypi && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          verbose: true

      - name: Upload to PyPI
        if: ${{ inputs.upload-to-pypi && (startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch') }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
