name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.10'
          activate-environment: true

      - name: Install Kumo RFM MCP
        run: uv pip install .

      - name: Install dependencies
        run: uv pip install mypy

      - name: Check type hints
        run: uv run --no-project mypy
