name: Publish Package

"on":  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      upload-to-testpypi:
        type: boolean
        required: false
        default: false
        description: "Upload to TestPyPI"
      upload-to-pypi:
        type: boolean
        required: false
        default: false
        description: "Upload to PyPI"
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: |
          python -m build

      - name: Validate built packages
        run: |
          ls -ahl dist/
          ./scripts/validate_wheels_for_release.sh

      - name: Upload to TestPyPI
        if: ${{ inputs.upload-to-testpypi || github.event_name == 'workflow_dispatch' }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          verbose: true

      - name: Upload to PyPI
        if: ${{ inputs.upload-to-pypi || startsWith(github.ref, 'refs/tags/v') }}
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
